name: Tests

on: pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Setup RSpec
        run: |
          gem install bundler:1.17.3
          [ -f Gemfile ] && bundle install
          gem install --no-document rspec:'~>3.10' httparty slack-ruby-bot
      - name: RSpec Report
        run: rspec --force-color --format documentation
